### ISSUE TITLE
BlogPostCard design changes for more info to user

### ISSUE THREAD

**Issue by devgoel186** [AeroDBPGC/website#15]
The blog post card currently looks like this:
![GIT2](https://user-images.githubusercontent.com/62515918/94923249-2d56a700-04d9-11eb-9d95-1c2aecf4f55f.PNG)

We can change it to add author info too for improved design
![GIT2](https://user-images.githubusercontent.com/62515918/94923875-3136f900-04da-11eb-8ca7-8c068256b210.PNG)

**Comment by bharat787** [comment]
lgtm

**Comment by devgoel186** [comment]
I am closing this issue now, as blog feature is removed from site.
