### ISSUE TITLE
Add contact links/Cards

### ISSUE THREAD

**Issue by bharat787** [AeroDBPGC/website#4]
In the 'Meet the team' section, tap to connect reveals the available contact methods to reach a member. Link these options to the relevant email ids/github accounts etc.
Also a few more contact cards need to added.

You may contact one of the project mentors (Bharat Gupta or Varun Bankar) to get these ids and card detalis

**Comment by devgoel186** [comment]
I'll take this issue.

**Comment by varunbankar** [comment]
Should we close this issue? @bharat787

**Comment by bharat787** [comment]
Ya i suppose for now there are no more updates to it, i was thinking we might add the member's intro kinda thing that'll be later
So closed for now.
